name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python3 -m pip install uv
        uv venv
        source .venv/bin/activate
        make install
    - name: Lint with flake8
      run: |
        source .venv/bin/activate
        make lint
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        make test
